### ISSUE TITLE
Shopping cart id instead of order ID

### ISSUE THREAD

**Issue by Andreas-81** [bambora/checkout-prestashop#1]
In bambora reports you get transaction for shopping cart id. It think it would be better to have order id. This would make it more easy to match the order in Bambora reports with order in Prestashop. 

We also had trouble with dublicate orders with this module. They get two order id. One of the order are missing transaction id and is not valid. Do you know why this happen? The same order has dublicate shopping carts with same id.

**Comment by AllanWLie** [comment]
Hi @Andreas-81 
This is not possible since the order id is first created after our payment system have received the cart data and returned with an approval to the shop which afterwards converts the cart to an order.  

-Allan
