### ISSUE TITLE
Order with Vipps payment

### ISSUE THREAD

**Issue by Andreas-81** [bambora/checkout-prestashop#12]
Order with Vipps payment are showing Bambora Checkout (VISA (Debit / Domestic))  instead of Vipps. 
![image](https://user-images.githubusercontent.com/57504588/224266147-c1dace87-1687-479a-bfd6-896cc1321c1f.png)

**Comment by sessan** [comment]
Hi! Have you reported this to support? (Please mention my name to them so they can forward the more information that we cannot share here. And does the transaction look alright in the Merchant Tool? I'm not sure it actually is a Prestashop issue. @Andreas-81 
Best Regards
Jessica Björkäng, Bambora Online

**Comment by Andreas-81** [comment]
Transaction looks good in merchant tool. I will send informasion to worldline :)

**Comment by sessan** [comment]
Hi @Andreas-81! 
The Wallet-payments (Vipps amongst others) are still considered a card payment so it's not really a bug. The info that it also is a Wallet payment has not been implemented in the open source modules yet. We will add that to the list of things to improve. Hope to get it out soon! 
Best regards
Jessica
