### ISSUE TITLE
Vipps payment

### ISSUE THREAD

**Issue by Andreas-81** [bambora/checkout-prestashop#2]
If you try to pay with vipps and you did not confirm with the phone by misstake it is not possible to make Vipps payment again. It seems you only have one try.

You also have two steps to make the payment with Vipps. First you fill your phone number en hit "Pay/ok" then you go to Vipps and have the same step. Is it possible to remove one of the steps when they are both the same?

**Comment by AllanWLie** [comment]
Hi @Andreas-81 

We are aware of the issue and it will be fixed in a future release of the payment window. 

Thank you and have a good day.

Best regards
Allan
