### ISSUE TITLE
Missing payment details in PDF invoice

### ISSUE THREAD

**Issue by runemart** [bambora/checkout-prestashop#3]
The module adds transaction id, payment type and card number to the PDF invoice. 
This works as expected when downloading PDF invoices from the list of orders. 
However, in the email that is sent to the customer, these fields are empty. 
(The three titles are inserted into the PDF invoice, but not the actual data). 

Running PrestaShop 1.7.6.6 with version 1.6.3 of the module. 

![Merknad 2020-08-28 144128](https://user-images.githubusercontent.com/117179/91561874-96785700-e93c-11ea-8031-8c506395f2b9.png)

**Comment by sessan** [comment]
This issue is now fixed in the latest release 1.8.2
