### ISSUE TITLE
Unable to delete payment before capture on 1.7.1

### ISSUE THREAD

**Issue by onklmaps** [bambora/checkout-prestashop#4]
There is no way to delete a payment before it's captured. 
I get error message: 
![Screenshot 2020-11-11 at 09 41 41](https://user-images.githubusercontent.com/30602638/98789272-5d5f6700-2402-11eb-90ac-d3e346ee4c8a.png)

There is no way to enter an amount.

**Comment by AllanWLie** [comment]
@onklmaps 
This is solved in release 1.8.1
