### ISSUE TITLE
Payment window backoffice order

### ISSUE THREAD

**Issue by Andreas-81** [bambora/checkout-prestashop#5]
The payment window could be wider on order view. look at picture below. Prestashop v.1.7.6.7, Bambora v.1.8.1

![image](https://user-images.githubusercontent.com/57504588/108818343-84106a80-75b9-11eb-9414-90f42412ac1e.png)

**Comment by Andreas-81** [comment]
Tittel missing and window should have been 100% wide?

**Comment by sessan** [comment]
This issue is now fixed in the latest release v.1.8.2

**Comment by Andreas-81** [comment]
Thanks :)
