### ISSUE TITLE
Multi-Store Support?

### ISSUE THREAD

**Issue by mehov** [bambora/checkout-prestashop#7]
Hello everyone,

We're considering Prestashop. Quick question: does your Prestashop extension support  [multistore setups](https://doc.prestashop.com/display/PS16/Managing+Multiple+Shops)?

Your [Step-by-step video guide](https://www.youtube.com/watch?v=tqjqW82wYTQ) [here](https://developer.bambora.com/europe/shopping-carts/shopping-carts/prestashop) shows a set of inputs only for one merchant (although, chances are that demo store isn't a multistore, and the extension simply may have recognised that).
![bambora prestashop module setup](https://user-images.githubusercontent.com/7813306/137320338-ad5ed52b-e8e7-44c7-ac12-711fb90a1a0d.png)

The reason I ask is it's Opencart counterpart [doesn't support multiple shops](https://github.com/bambora/checkout-opencart/issues/6), and our Bambora account manager doesn't care and insists on using separate merchant IDs for every domain name connected to that store, which is impossible when the extension is asking for the credentials for just 1 merchant.

(We ourselves don't care and we would happily use just one set of credentials of one merchant ID across all domain names.)

**Comment by sessan** [comment]
@mehov as I mentioned in the Opencart-discussion we are now looking into this.
