### ISSUE TITLE
Send ordre id to Bambora

### ISSUE THREAD

**Issue by Andreas-81** [bambora/checkout-prestashop#9]
Today module use shopping cart id from Prestashop to Bambora transaction list. This is in reports.bambora.com etc. Hope you can update this to order ID from Prestashop when the order is placed. It is very hard to associate the payment with shopping cart id.

**Comment by sessan** [comment]
Hi @Andreas-81. A solution for you could be to follow what they recommend here:
https://scelliuspaiement.labanquepostale.fr/doc/en-EN/faq/how-to-manage-the-prestashop-order-id.html 
This way you will see the cart-id in the admin and hence be able to associate it with an order id. 

Best Regards
/Jessica, Bambora Online
